In [1]:
import tensorflow as tf

In [2]:
tensor = tf.constant([
    [1, 2],
    [3, 4]
])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [3]:
tf.__version__

'2.8.0'

In [4]:
tensor.shape

TensorShape([2, 2])

In [5]:
import numpy as np

In [6]:
tensor_np = tensor.numpy()

In [7]:
tensor_np

array([[1, 2],
       [3, 4]])

In [11]:
np_array = np.random.randint(3, 9, size=(3, 3))

In [12]:
np_array

array([[6, 6, 7],
       [8, 4, 5],
       [4, 7, 7]])

In [13]:
tensor2 = tf.constant(np_array)

In [14]:
tensor2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[6, 6, 7],
       [8, 4, 5],
       [4, 7, 7]])>

In [15]:
tf_variable = tf.Variable([
    [1.0, 2, 3],
    [4, 5, 6]
])

In [16]:
tf_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [17]:
tf_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [18]:
tf_variable[1, 1].assign(40)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 1.,  2.,  3.],
       [ 4., 40.,  6.]], dtype=float32)>

In [19]:
tf_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 1.,  2.,  3.],
       [ 4., 40.,  6.]], dtype=float32)>

In [20]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [21]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]])>

In [22]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [23]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]])>

In [24]:
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]])

In [25]:
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [26]:
tensor2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[6, 6, 7],
       [8, 4, 5],
       [4, 7, 7]])>

In [27]:
tensor3 = tf.constant(np.random.randint(0, 4, size=(2, 2)))

In [28]:
tensor3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [1, 2]])>

In [29]:
tensor @ tensor3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  7],
       [ 7, 17]])>

In [30]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [31]:
tf_string = tf.constant("TF")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'TF'>

In [32]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [33]:
tf.strings.unicode_decode(tf_string, 'UTF8')

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([84, 70])>

In [34]:
ord('T')

84

In [35]:
tf_str_arr = tf.constant([
    "TF", "is", "good"
])
for s in tf_str_arr:
    print(s)

tf.Tensor(b'TF', shape=(), dtype=string)
tf.Tensor(b'is', shape=(), dtype=string)
tf.Tensor(b'good', shape=(), dtype=string)
